### ISSUE TITLE
Unsupported JavaFX configuration 

### ISSUE THREAD

**Issue by Shinusagi** [developersu/ns-usbloader#123]
I usually opened the application “ns-usbloader” and worked just fine on my Manjaro distro to connect to the Switch… however it stopped working, or better said it still open but it doesn’t seem to connect anymore with the Nintendo Switch anymore via USB

The error I get from running it directly over the console is this one:

manjaro@Manjaro-PC: sudo ns-usbloader
Jun 26, 2022 12:58:20 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from ‘unnamed module @774bd0a2’

I uninstalled EVERYTHING java related, even stuff that forced me to uninstall also other apps but I get rid of Java and then after a reboot and clean of orphan packages I installed only the JRE from the repos and Azul Zulu JRE which comes with JafaFX… but I got the same results

After that I checked the libusb1 but it is installed already, so I have no clue what the Java issue is, I found information about running modules and other stuff but it kind of lost me. I tried execting the ns-usbloader using the legacy version but nothing changes, I also installed it from the repos as well and I get the same result.
Asked on Manjaro forums but it seems more specific to the app so I came here so maybe someone can give me a hand with this please.

**Comment by developersu** [comment]
Hi
Thank you for reporting.
These JavaFX-related messages are not that important. I see the same. As for JDK/JRE: you should be good with manjaro's default OpenJDK 11, for example.

Did you created setup for 'udev'? It's should be created in case you've installed app from AUR.
Also please try to run application as root. If it helps then udev is a thing.

**Comment by NeutralAlice** [comment]
wondering if they didn't post the full bit and instead just posted the first snippet. I get the same first bit of snippet, and guessing it has to do with running this on wayland without X11. 

Here's my full error on Arch linux(have udev rules)
`Oct 29, 2022 10:42:38 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @59487e7'
Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

Exception in thread "main" java.lang.UnsupportedOperationException: Unable to open DISPLAY
	at com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(GtkApplication.java:202)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:200)
	at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
	at com.sun.glass.ui.Application.run(Application.java:146)
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:290)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:293)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:1589)`

**Comment by developersu** [comment]
It's full snipped originally posted, but for X11 setup. 
I didn't test it without having X11 behind so, I you're correct. JavaFX devs should be taking care of wayland support.

**Comment by Cueropedo** [comment]
Not sure if it's related, but on Clear Linux OS on wayland this happens if I try to open it via a ".sh" I made for opening in the GNOME launcher (.desktop file)

[Screencast from 2023-11-24 22-46-10.webm](https://github.com/developersu/ns-usbloader/assets/64707859/241ead23-c8b9-4c3d-b5ca-133693cc66b4)

However ns-usbloader opens fine if I manually type the command in console without using the script.
