### ISSUE TITLE
M1. Success connection on Switch. Sending nsp in computer. Nothing happens.

### ISSUE THREAD

**Issue by rmvz3** [developersu/ns-usbloader#138]
v6.0 used to work perfectly in my M1 but after upgrading to v7, it doesn't work at all. Everything seems to be ok but the Switch app is waiting for the mac to send it the nsp file and the mac is waiting for the Switch to receive it.

Is there something I can do? Maybe I need to install anything else? I have already installed (up to date) libusb and I've installed the jdk-19-arm64.dmg from oracle.

**Comment by developersu** [comment]
mm.. try to reboot mac and switch or use another cable/USB port. 
I don't know what could it be.

**Comment by tauba** [comment]
facing the same issue here, everything seems to be working, but when I send it to switch, it says "connection successful, waiting for files to be send "

**Comment by tauba** [comment]
Sorry, my bad

I did the "brew install libusb" and it solved the issue

worked fine now

**Comment by moseslucas** [comment]
Same here. even reinstalling `libusb` I'm stil stuck in `Waiting for list of files to be sent...` in Awoo Installer.

**Comment by moseslucas** [comment]
Was able to work but using the NET.
So In my Switch Awoo, I click via Internet.
Then in my NB USB LOADER on my Mac M1, at the top there's two dropdown fields.  I've selected:
* Awoo
* NET
* IP Address: Value that is shown in my switch Awoo

Clicking Upload worked immediettley but it's slower than usb transfer.

**Comment by developersu** [comment]
@moseslucas Did usb method worked before? I mean in previous versions.

**Comment by moseslucas** [comment]
@moseslucas  This is my first time doing this and am already at version 7 ns-usbloader. So, No.

**Comment by developersu** [comment]
@moseslucas 
Ok.. actually I don't know what is this, but here are the steps I'd do:
1. Reboot switch.
2. Start hbmenu via title: By pressing 'R' start any title installed.
3. Plug usb-c/usb-c cable (make sure it's good one)
4. Start awoo, select usb
5. Start ns-usbloader and try again.

For instance in linux Awoo in USB mode works for me a bit strange: like it works only first time and after that I have to restart 'title-mode' and awoo.

Also try another awoo-based apps. Like the one shipped with Team-Neptune/DeepSea.

**Comment by Jean-Daniel** [comment]
Same here. Fails with the following exception:

```
java.lang.NullPointerException: Cannot invoke "java.io.File.isDirectory()" because "nspFile" is null
	at nsusbloader.com.usb.TinFoil.fileRangeCmd(TinFoil.java:180)
	at nsusbloader.com.usb.TinFoil.proceedCommands(TinFoil.java:135)
	at nsusbloader.com.usb.TinFoil.<init>(TinFoil.java:58)
	at nsusbloader.com.usb.UsbCommunications.run(UsbCommunications.java:67)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by developersu** [comment]
Looks similar to #73

**Comment by Corcho911** [comment]
did someone could solve this problem?

i have an imac 2021 M1, and i cant use nsusbloader, I already tried it all. Use to work with Windows and i could run ok the program.

**Comment by Jean-Daniel** [comment]
> u did it on a mac m1? how can u i that?

Install [brew](https://brew.sh) and use it to install libusb

**Comment by Corcho911** [comment]
> > u did it on a mac m1? how can u i that?
> 
> Install [brew](https://brew.sh) and use it to install libusb

already did that, now my switch detects the game i want to install, but it gives me an error. 
![WhatsApp Image 2023-04-19 at 11 50 20](https://user-images.githubusercontent.com/131034583/233114096-a9111cc9-6320-4cc7-9790-9887e165db47.jpeg)

**Comment by Corcho911** [comment]
it stays in 0.00 MB/s untill says that the installation fails. :(

before brew install libusb my switch didnt recognize the game, now it does but i cant install it

**Comment by asyba** [comment]
FYI: I never could make it work ns-usbloader with mac m1, so I used DBI installer with MTP method.

**Comment by rmvz3** [comment]
I was unable to make it work either. But I found an Apple Silicon compiled version elsewhere (maybe Reddit) which works flawesly

**Comment by developersu** [comment]
@rmvz3 if it works then attach downloaded jar here. We'll check.
Thanks!

**Comment by rmvz3** [comment]
Well, in fact it's not a jar but a macOS .app I don't know if you'll be able to get something useful from it but… there you have: https://www.icloud.com/iclouddrive/00eHCv5IwmMIMsmsMQyt412_g#NS-USBloader

**Comment by Corcho911** [comment]
> Well, in fact it's not a jar but a macOS .app I don't know if you'll be able to get something useful from it but… there you have: https://www.icloud.com/iclouddrive/00eHCv5IwmMIMsmsMQyt412_g#NS-USBloader

thanks, i download it but it gives me an error.

The error in spanish says:
La acción “Ejecutar el script Shell” detectó un error: “zsh:1: no such file or directory: /Applications/NS-USBloader.app/Contents/PlugIns/jdk-11.0.16.1.jdk/Contents/Home/bin/java”

**Comment by rmvz3** [comment]
> thanks, i download it but it gives me an error.

Hmmm… I don't know why could this happen. I've checked the file in the zip and it has these files included (just select Show content in the contextual menu and you'll be able to check it). Maybe it's any kind of permission problem

**Comment by developersu** [comment]
It's just version 6.1 wrapped into 'app' with java runtime inside.

**Comment by rmvz3** [comment]
Yes, I see (never looked inside the app until now). So, if I replace the jar with the latest version… it should work, right?

**Comment by developersu** [comment]
Mmm.. I don't know.. 
JDK inside is for intel's x86_64, so I guess you'll run it in 'emulation' mode, therefore the library you'll use would be the one pre-compiled for x86_64 as well.
I'd say, there is a chance that it would be working for you (in case now it works with 6.1 jar) but not necessarily for others.

**Comment by rmvz3** [comment]
It works! I've just edited the .workflow file (automator script) to remove the version reference in the jar file so it just looks for "ns-usbloader.jar" instead of "ns-usbloader_6.5.jar" to be easier to update. Added the new 7.0 version renamed that way and it worked. Some caveats: the m1 jar version doesn't work (some problem with javafx if I remember), it must be the "regular" one ("ns-usbloader-7.0.jar"). Also, the app MUST be in Application folder, otherwise it will fail to find the hardcoded paths, which is what happened to @Corcho911 (not very elegant code but at least it works).

**Comment by Corcho911** [comment]
> It works! I've just edited the .workflow file (automator script) to remove the version reference in the jar file so it just looks for "ns-usbloader.jar" instead of "ns-usbloader_6.5.jar" to be easier to update. Added the new 7.0 version renamed that way and it worked. Some caveats: the m1 jar version doesn't work (some problem with javafx if I remember), it must be the "regular" one ("ns-usbloader-7.0.jar"). Also, the app MUST be in Application folder, otherwise it will fail to find the hardcoded paths, which is what happened to @Corcho911 (not very elegant code but at least it works).
> 
> EDIT: This is the updated 7.0 version in case anyone want it: https://www.icloud.com/iclouddrive/0a04OJObLcgyIo5XzCk8B-kqQ#NS-USBloader



hey thanks for all, but same error still. I will buy a pc

**Comment by rmvz3** [comment]
> I will buy a pc

Unrelated to the issue. Also, then you WILL have a lot of problems XDDD

**Comment by Masamune3210** [comment]
Not anymore than any other computer would have. If you want to just use windows for a couple of things, just virtualize it

**Comment by zcg331793187** [comment]
same issue.

**Comment by inzar98** [comment]
Just use Azul jdk19. it solves issue perfectly
