### ISSUE TITLE
Installing ns-usbloader on macos m1

### ISSUE THREAD

**Issue by ghubcop** [developersu/ns-usbloader#151]
I installed java sdk on this website: https://www.oracle.com/java/technologies/downloads/#jdk21-mac. Then I downloaded and opened the latest m1 .jar file and nothing happens. It says "Java Application launch failed. Check Console for possible error messages related to .jar". I tried the linux section but I don't really understand how it's supposed to work. What am I missing? Should I downgrade java to jdk 19?

**Information about environment (mandatory):**
 - OS: 13.5 Beta (22G5048d)
 - Java version: 21

**Comment by developersu** [comment]
Well, run it from console `java -jar .../app_name.jar` and paste output here.
Or install Azul JDK 19. People with m1 macs says it's better.

**Comment by Jake-Arnold** [comment]
Having the same issue. 

`Exception in thread "main" java.lang.UnsupportedClassVersionError: nsusbloader/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:632)
`

**Comment by izenn** [comment]
just installed this today using java from brew.

open a terminal and then do the following: 
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew install temurin
export JAVA_HOME=`/usr/libexec/java_home -v 21`; java -version
java -jar ns-usbloader-7.0-m1.jar
```

**Comment by secretjupiter** [comment]
On M1 Mac you need to manually install libusb, see the [release notes of v7](https://github.com/developersu/ns-usbloader/releases/tag/v7.0).

Simply run the following command ([Homebrew](https://brew.sh/) is needed):
`brew install libusb`
