### ISSUE TITLE
Cannot install nsz, Tinfoil Exception is thrown

### ISSUE THREAD

**Issue by carlosen14** [developersu/ns-usbloader#73]
**Describe the bug (mandatory)**
Crash when uploading a `.nsz` rom.

**Information about environment (mandatory):**
 - OS: Ubuntu 18.04 x64
 - Switch: FW 10.0.4, Atmosphere 0.13.0-master-32951329
 - Java version: openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)

**Steps to reproduce**
1. On Switch, go to Awoo Installer v1.3.3
2. Select 'Install over USB'
3. On NS-USBloader v4.2, click on 'Select file' **also tried the legacy version, same result**
4. Click 'Upload to NS'
5. On switch, a message will appear to select the incoming files to install
6. Select to install on SD Card
7. Here throws an exception!!

**Expected behavior**
A clean install was expecting.

**Screenshots and/or information from application log**
Have this log on terminal even running the same steps
Sometimes this log, when this appears, i get into Atmosphere OS Exception screen, and Switch needs to be rebooted.
```
java.io.IOException: TF Failure during file transfer.
	at nsusbloader.COM.USB.TinFoil.sendNormalFile(TinFoil.java:262)
	at nsusbloader.COM.USB.TinFoil.fileRangeCmd(TinFoil.java:189)
	at nsusbloader.COM.USB.TinFoil.proceedCommands(TinFoil.java:135)
	at nsusbloader.COM.USB.TinFoil.<init>(TinFoil.java:58)
	at nsusbloader.COM.USB.UsbCommunications.run(UsbCommunications.java:67)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
Some times this other log, when this logs appears, i remain on Awoo Installer.
```
java.lang.NullPointerException
	at nsusbloader.COM.USB.TinFoil.fileRangeCmd(TinFoil.java:180)
	at nsusbloader.COM.USB.TinFoil.proceedCommands(TinFoil.java:135)
	at nsusbloader.COM.USB.TinFoil.<init>(TinFoil.java:58)
	at nsusbloader.COM.USB.UsbCommunications.run(UsbCommunications.java:67)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
**Did you see this issue in previous versions?**
First time using this

**Additional context**
hbmenu appears **Applet Mode** as always, but even this it worked before with Goldleaf v0.7.3

**Comment by carlosen14** [comment]
copied the `.nsz` files to sdcard, and installation was successful.

**Comment by carlosen14** [comment]
I could split some nsz rom, copied to sdcard, but .nro installer can't handle it, amm, how it is supposed to installed when splitted?

**Comment by developersu** [comment]
First of all thanks for detailed report.

Secondly, there is log-section in app: latest tab where icon has three dots. Usually it contains a bit more detailed output.

> Sometimes this log, when this appears, i get into Atmosphere OS Exception screen, and Switch needs to be rebooted.

Maybe it's an issue with cable or usb port. Like it's usb type-c cable or usb type-c port (I don't have any so I have no idea). Or it could be just a bad cable. Issues related to cables happens very often. I checked a part of code related to this issue and what you see means that there is something wrong happened in a moment application tried to write data. Drop me logs from 'three-dots-tab'. It would be really helpful.

_...Also legacy and ordinary version doesn't make any difference on Linux hosts (AFAIK).
It could be an issue inside OpenJDK, but I don't think so..._ 

As for the second terminal log you gave me: it's really strange. Maybe (!) if you rename file so something latin letters only it would solve this issue (e.g. 'myfile.nsz'). Also logs from 'three-dots-tab' would be helpful here.

> hbmenu appears Applet Mode as always, but even this it worked before with Goldleaf v0.7.3

Awoo-Installer is recommended to start in different mode. I don't remember how it's called, but to enter it you have to click 'R' and start ANY game while holding 'R' button.

> I could split some nsz rom, copied to sdcard, but .nro installer can't handle it, amm, how it is supposed to installed when splitted?

No idea. Never did it using Awoo Installer. From my app I guess you can't do it.. since it doesn't allow to select any folder that doesn't have '.nso' in the end of the name. Do you need this function? Or someone else?

**Comment by unbranched** [comment]
I have a similar problem, app doesn't crash but can't transfer any file after usb connects.
Goldleaf hangs before I should see the nsp info dialog (after choosing the install location). Awoo fails with error starting the transfer.
Same IOException error. Tried different usb port, didn't try another usb cable but it always worked...

My setup:
Arch Linux
openjdk jre 15
Switch fw 10.2.0, Athmosphere 0.15.0
