### ISSUE TITLE
Ns-USBLoader 4.4 isn't opening

### ISSUE THREAD

**Issue by tefanga** [developersu/ns-usbloader#81]
**Describe the bug (mandatory)**
Previous versions opened fine. This new version 4.4 isn't opening.

**Information about environment (mandatory):**
 - OS: Windows 10 - 64bits
 - Java version: 1.8.0_271

**Steps to reproduce**
Just downloaded it 2 times, dosn't open.

**Expected behavior**
Open the ns-usbloader screen.

**Did you see this issue in previous versions?**
No

**Comment by developersu** [comment]
Hi

Please start if from cmd.exe like 'java -jar C:\User\you_here\Downloads\applicaion.jar' and copy output here.

Also try 'java -jar C:\User\you_here\Downloads\applicaion.jar -c' to reset application settings.

Thanks!

**Comment by tefanga** [comment]
Output:
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$1(LauncherImpl.java:182)
        at java.lang.Thread.run(Unknown Source)
Caused by: javafx.fxml.LoadException:
file:/C:/Users/tefa/Hack%20Nintendo/ns-usbloader-4.4.jar!/GamesTab.fxml
file:/C:/Users/tefa/Hack%20Nintendo/ns-usbloader-4.4.jar!/NSLMain.fxml:26

        at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2579)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
        at javafx.fxml.FXMLLoader.access$2700(FXMLLoader.java:103)
        at javafx.fxml.FXMLLoader$IncludeElement.constructValue(FXMLLoader.java:1143)
        at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:746)
        at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2707)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
        at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
        at nsusbloader.NSLMain.start(NSLMain.java:46)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:187)
        ... 1 more
Caused by: java.nio.file.InvalidPathException: Illegal character [?] in path at index 2: \\?\D:\Juegos de SWITCH\South Park - The Stick of Truth & The Fractured But Whole\South Park The Stick of Truth + The Fractured but Whole [NSZ]\South Park The Fractured but Whole\Update 1.05
        at sun.nio.fs.WindowsPathParser.nextSlash(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPath.parse(Unknown Source)
        at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at java.nio.file.Paths.get(Unknown Source)
        at nsusbloader.FilesHelper.getRealFolder(FilesHelper.java:27)
        at nsusbloader.AppPreferences.getRecent(AppPreferences.java:64)
        at nsusbloader.Controllers.GamesController.initialize(GamesController.java:150)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2548)
        ... 18 more

I think is stuck on the folder last opened. Like I said on my last issue post when select file nsp wasn't working.

Reseting the application settings worked fine.
Now its open. So for people that had the problem "select nsp file" wasn't working/opening in 4.3, now on 4.4 won't open the app. This fixed the problem in someway.

Thanks for the support

**Comment by developersu** [comment]
Thanks for details! Really helped to find out issue =)

**Comment by xXxQuiquexXx** [comment]
hahaha and all because my friend @tefanga
did not recreate the previously deleted folder!

Release 4.3 started without problems for me

but I guess now the correction is better! :)
