### ISSUE TITLE
Cannot invoke "java.io.File.isDirectory()" because "nspFile" is null

### ISSUE THREAD

**Issue by scalp42** [developersu/ns-usbloader#94]
Hi folks,

Using v5.0 (non legacy), ran into the following issue:

```
         Offset: 35264                0x89c0
         Size:   3072                 0xc00
[ FAIL ] TF NullPointerException (in some moment application didn't find something. Something important.):
         Cannot invoke "java.io.File.isDirectory()" because "nspFile" is null
[ INFO ] 	End
```

**Comment by Fatih120** [comment]
Running v5.2 on Fedora with OpenJDK 17. I am getting this error as well even after installing single files. No clue if this log is of any use:

```
java.lang.NullPointerException: Cannot invoke "java.io.File.isDirectory()" because "nspFile" is null
        at nsusbloader.com.usb.TinFoil.fileRangeCmd(TinFoil.java:180)
        at nsusbloader.com.usb.TinFoil.proceedCommands(TinFoil.java:135)
        at nsusbloader.com.usb.TinFoil.<init>(TinFoil.java:58)
        at nsusbloader.com.usb.UsbCommunications.run(UsbCommunications.java:67)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by developersu** [comment]
Thank you for this observation.
Does it happens with every file you're trying to install? Does this NSP actually installed?

**Comment by developersu** [comment]
Great idea. Thanks!
